### ISSUE TITLE
Menu items moved into hamburger menu could use space far better in a two column lay out

### ISSUE THREAD

**Issue by AndyatFocallocal** [sylque/discourse-custom-header-links2#1]
![Screenshot_2019-07-03-02-11-35-896_com android chrome](https://user-images.githubusercontent.com/16229696/60591892-b72c3780-9d9f-11e9-9c86-d89b73a4007e.png)

Lots of white space. Two columns would use space better

**Comment by sylque** [comment]
Fixed since version https://github.com/sylque/discourse-custom-header-links2/commit/085b09a480bb44aea93e21c8bdf1dfd7bf243c9a.
